// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBToqSz7CiPZeR9561D9VDvV79DjGZROsE',
    appId: '1:163565476171:web:03dbea1365787d972af0ce',
    messagingSenderId: '163565476171',
    projectId: 'foodiehub-e8805',
    authDomain: 'foodiehub-e8805.firebaseapp.com',
    storageBucket: 'foodiehub-e8805.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl7WuEkOmOhdnwBokph3IfJ7clrIATX80',
    appId: '1:163565476171:android:e57d48f3596f14592af0ce',
    messagingSenderId: '163565476171',
    projectId: 'foodiehub-e8805',
    storageBucket: 'foodiehub-e8805.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYLMLE1ZIjjwd3qnESdWf_uX3jLy0Yf94',
    appId: '1:163565476171:ios:f68b96a402b1eb542af0ce',
    messagingSenderId: '163565476171',
    projectId: 'foodiehub-e8805',
    storageBucket: 'foodiehub-e8805.firebasestorage.app',
    iosBundleId: 'com.example.foodiehub',
  );
}
